version: "3.9"
services:
  postgres:
    image: postgres:13-bullseye
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql
volumes:
  postgres_data:
